entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: resolver1
api:
  insecure: true
providers:
  docker: {}
certificatesResolvers:
  resolver1:
    acme:
      email: abarrei@gmail.com
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: acme.json
      tlsChallenge: {}
log:
  level: DEBUG
